asdf

diff --git a/increase_version_number b/increase_version_number
--- a/increase_version_number
+++ b/increase_version_number
@@ -112,7 +112,7 @@ if [ "${MAJOR_MINOR}" != "${MINOR}" ] && [ "${MAJOR_MINOR}" != "${MAJOR}" ]; the
 fi
 
 # Get current version and parse it to components
-current_version_number=`./get_version_number`
+current_version_number=`./get_version_number --long`
 if [ "${?}" != "0" ]; then
     echo
     echo "Error: failed to get current version number (by 'get_version_number' command)."
@@ -138,11 +138,12 @@ if [[ $v1 =~ ^[[:digit:]]+$ ]] && [[ $v2 =~ ^[[:digit:]]+$ ]] && [[ $v3 =~ ^[[:d
 else
     echo
     echo "Error: version component sanity check DID NOT PASS! Please fix."
-    echo "       Details: version compontnts:"
+    echo "       Details: version components:"
     echo "					v1: '${v1}'"
     echo "					v2: '${v2}'"
     echo "					v3: '${v3}'"
     echo
+    exit 1
 fi
 
 
@@ -187,58 +188,12 @@ else
     fi
 fi
 
-echo git tag -a ${next_version_number} -m "Version tag ${next_version_number} applied on ${YYYYMMDD_HHMM} by user '${WHOAMI}'."
-
-exit 0
-
-# commit & push to github all the changes
-COMMIT_MESSAGE="${GIT_TAG} published by user `whoami` on `date`."
-if [ "${COMMIT_COMMENT}" != "" ]; then
-    COMMIT_MESSAGE="${COMMIT_MESSAGE} ${COMMIT_COMMENT}"
-fi
-git commit -m "${COMMIT_MESSAGE}"
+git tag -a ${next_version_number} -m "Version tag ${next_version_number} applied on ${YYYYMMDD_HHMM} by user '${WHOAMI}'."
 if [ "$?" != "0" ]; then
-    echo
-    echo "Error: failed to git commit"
-    echo
+    echo "Error: failed to apply new version number"
     exit 1
-else
-    echo "git commit succeed (code: ${res})"
 fi
 
-git push
-if [ "$?" != "0" ]; then
-    echo
-    echo "Error: failed to git push"
-    echo
-    exit 1
-else
-    echo "git push succeed (code: ${res})"
-fi
-
-
-# # review tags
-# git tag
-
-echo "create new tag '${GIT_TAG}'"
-git tag $GIT_TAG
-
-echo "upload new tag to github"
-git push origin --tags
-if [ "$?" != "0" ]; then
-    echo "Error: failed to git push tags"
-    exit 1
-else
-    echo "git push tags succeed (code: ${res})"
-fi
-
-# review status
-git status
-
-echo "***************************************** success! *****************************************"
+echo "New version number successfully applied"
 echo
-echo "${COMMIT_MESSAGE}"
-echo 
-
-# return success
 exit 0
